apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
bases:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.7.3/manifests/install.yaml
resources:
  - resources/namespace.yaml
patchesStrategicMerge:
  - patches/argocd-cm.yaml